import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Script from 'next/script'
import transitionScript from './intro.js'
import comet from '../public/comet.svg'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Script strategy='beforeInteractive' src={transitionScript}></Script>
      <main id='introMain' className={styles.main}>
        <h1 id='introName' className={`${styles.title} ${styles.nameCredit}`}>
          White Comets
        </h1>
        <h1 id='introWelcome' className={`${styles.title} ${styles.welcomeCredit}`}>
          Welcome, to the world of the grandeaurs
        </h1>

      </main>
      <section>


      </section>
    </div>
  )
}
